module.exports = {
  title: "devtab",
  description: "안녕하세요!",
  author: "devtab",
  siteUrl: "https://devtab.netlify.app/",
  links: {
    github: "https://github.com/DHkimgit",
    blogger : "https://velog.io/@devtab/posts",
    // linkedIn: "https://linkedin.com",
    // facebook: "https://www.facebook.com",
    // twitter: "https://twitter.com",
    // x: "https://x.com",
    // instagram: "https://www.instagram.com",
    // medium: "https://medium.com",
    // blogger: "https://blogger.com",
    email: "mailto:dukekim001@naver.com",
    // resume: "https://hudi.blog",
    // link: "https://hudi.blog",
  },
  useAbout: true,
  // See https://giscus.app/
  giscus: {
    repo: "DHkimgit/blog",
    repoId: "MDEwOlJlcG9zaXRvcnkzNjk4NjMzNTg=",
    category: "Comments",
    categoryId: "DIC_kwDOFguqvs4ChwGy",
    mapping: "pathname",
    strict: "0",
    reactionsEnabled: "1",
    inputPosition: "bottom",
    lang: "en",
  },
}
